### ISSUE TITLE
Support bitbucket cloud origins

### ISSUE THREAD

**Issue by thisgeek** [tommcdo/vim-fubitive#11]
I would like to be able to use fugitive with my hosted bitbucket.

Is it already possible to set the fugitive_bitbucket_domains variable in some way to make this work?

**Comment by tommcdo** [comment]
Yes, you should be able to put something like this in your `.vimrc` file:

    if !exists('g:fugitive_bitbucket_domains')
        g:fugitive_bitbucket_domains = []
    endif
    let g:fugitive_bitbucket_domains += ['my.hosted.domain.com']

Or, if you don't care about any previous domains from that global List, you can just do this:

    let g:fugitive_bitbucket_domains = ['my.hosted.domain.com']

**Comment by thisgeek** [comment]
Couple notes, for posterity:

When I said "bitbucket cloud", I meant "bitbucket server".

The bitbucket version I'm using is 4.10.1, which appears to have a different URL pattern that bitbucket.org's.

bitbucket.org example:

```
https://bitbucket.org/ludovicchabant/vim-lawrencium/src/c9169233d45ae2f0fefa0feb9ee816a87c6b05c8/ftplugin/hglog.vim?at=default&fileviewer=file-view-default#hglog.vim-5:7
```

My server example:

```
https://projects.example.com/bitbucket/projects/BB/repos/some-project/browse/.gitignore?until=656ea8ac146a064c279f35182946af7703c6880f&untilPath=.gitignore#2-4
```

So the way fubitive assembles the browse URL doesn't quite work for my use case.
