### ISSUE TITLE
fugitive: 'origin' is not a supported remote

### ISSUE THREAD

**Issue by kevintaylor** [tommcdo/vim-fubitive#12]
FYI, I was getting the "fugitive: 'origin' is not a supported remote" message using bitbucket with the bitbucket fugitive extension. Mac High Sierra, GVim and terminal Vim.

$ git --version
git version 2.15.0

$ git remote -v
origin	user@bitbucket.org:user/proj.com.git (fetch)
origin	user@bitbucket.org:user/proj.com.git (push)

To get Gbrowse to work, I needed to add https:// in .git/config, so
$ git remote -v
origin	https://user@bitbucket.org:user/proj.com.git (fetch)
origin	https://user@bitbucket.org:user/proj.com.git (push)

**Comment by somini** [comment]
With the code you posted, the top URL use SSH, while the bottom use HTTPS.

**Comment by mark2185** [comment]
@kevintaylor I take it this isn't an issue anymore?
