### ISSUE TITLE
Broken paths

### ISSUE THREAD

**Issue by kmARC** [tommcdo/vim-fubitive#14]
So I'm not sure whether these issues are monitored at all, or if this project is still being worked on, however...

This plugin is not at all working with my org's Bitbucket installation. I updated the script so that it works for the basics, here are the changes:

https://github.com/kmARC/vim-fubitive/commit/d97237f9a79c9fd234c0f174653ef35ae58cbb5d

It seems to work with our v4.9 (I'm not a maintainer / operator of our bitbucket installation.)

**Comment by rystaf** [comment]
Thank you! This worked great for our Bitbucket server as well. v5.12.0

**Comment by mark2185** [comment]
This was solved in #15 and fixed in #16, closing.

Feel free to reopen if something's not right :)
