### ISSUE TITLE
Changes made for configurable domains are incompatible with Bitbucket Cloud

### ISSUE THREAD

**Issue by jcypret** [tommcdo/vim-fubitive#16]
Hi 👋! I recently updated to the latest version of this plugin pulling in changes from PR #15. But it looks like those changes, bringing compatibility with Bitbucket Server, are incompatible with Bitbucket Cloud. I ran into the exact same issue @bdlangton describes here: https://github.com/tommcdo/vim-fubitive/pull/15#issuecomment-667323591.

I did some digging, and it looks like each, Cloud and Server, has a distinct URL structure:

* Bitbucket Cloud: `BASE_URL` / `OWNER` / `REPO` / src / `COMMIT` / `PATH` # `LINES`
* Bitbucket Server: `BASE_URL` / projects / `OWNER` / repos / `REPO` / browse / `PATH` ?at= `COMMIT` # `LINES`

But it looks like #15 changes the `root` to _always_ use the Bitbucket Server structure:

https://github.com/tommcdo/vim-fubitive/blob/d96f33e538ce47253ab8035be4a6c3a90963d312/plugin/fubitive.vim#L22

I found one mention of this distinction in https://github.com/tommcdo/vim-fubitive/issues/11#issuecomment-323234073, which describes the previous implementation being incompatible with Bitbucket Server.

### A couple of references I was able to find on the URL structures

Documentation on hyperlinking to source code in Bitbucket Cloud:
https://support.atlassian.com/bitbucket-cloud/docs/hyperlink-to-source-code-in-bitbucket

I was *not* able to find a comparable guide for Bitbucket Server, but I did some digging and found some good examples in Atlassian's official [VSCode plugin](https://bitbucket.org/atlassianlabs/atlascode). They have many references throughout the codebase [switching on `isCloud`](https://bitbucket.org/atlassianlabs/atlascode/src/8bcf7125af5495c46793dae3e3bf6ef448aaf4ce/src/commands/jira/createIssue.ts#lines-122:128):

```ts
return site.details.isCloud
  ? `${site.details.baseLinkUrl}/${site.ownerSlug}/${site.repoSlug}/src/${commit}${relativePath}${linesText ? `#lines-${linesText}` : ''}`
  : `${site.details.baseLinkUrl}/projects/${site.ownerSlug}/repos/${site.repoSlug}/browse${relativePath}?at=${commit}${linesText ? `#${linesText.replace(':', '-')}` : ''}`;
```
---

I'm happy to try and work out a PR, but didn't want to duplicate any efforts already underway. Also willing to test out and verify any fixes when ready. I've been using this plugin for a long while with no issue, so for now, just pinned my version to commit a4ec11e. Anyway, let me know if there's any way I can help. Thanks!✌️

**Comment by tommcdo** [comment]
Hey, thanks for taking the time to look into this and do all the research!

I haven't had a lot of time lately, so a PR would be much appreciated 😄

**Comment by kosciej16** [comment]
@jcypret I just noticed that problem - Do you work on that? Or should I create PR for that?
Our company uses bitbucket cloud and all paths are broken for me.
https://github.com/tommcdo/vim-fubitive/issues/14 this looks like change from cloud to server.
