### ISSUE TITLE
Problem with URL pattern

### ISSUE THREAD

**Issue by petrisch** [tommcdo/vim-fubitive#20]
Hi There

Maybe  this seems to break form time to time with Bitbucket.
But I'm not shure about the URL pattern.

If the code is at "https://mycompany.git.internal/project/XXX/repo/XXX"
Whats this "code\.example\.com" has to look like?

**Comment by mark2185** [comment]
Does this issue still occur?

The `g:fubitive_domain_pattern` in your case should look like `'mycompany\.git\.internal'`.

**Comment by petrisch** [comment]
Ah I now see the problem. If you are on a private network and TLS is not enabled, then there is no URL pattern recognised.
I tried to add it in a fork here: https://github.com/petrisch/vim-fubitive
taken me to the browser but still adding https in the url.
Feel free to ignore since most people will not want this anyway.

**Comment by mark2185** [comment]
Could you try putting a question mark in after `https` in the original code? I.e. `https?\=://`

If I'm right, that `?` should mean `zero or one previous character`, which in this case would mean that it matches both `http` _and_ `https`.

**Comment by mark2185** [comment]
Let's try to narrow it down - the pattern in question:
```
  let repo = matchstr(a:opts.remote,'^\%(https\=://\|git://\|\(ssh://\)\=git@\)\%(.\{-\}@\)\=\zs\('.domain_pattern.'\)[/:].\{-\}\ze\%(\.git\)\=$')
```
Matches both `http` and `https`, the `https\=` is the same as `https?` in other regex flavours.

What does `git remote -v` return in your repo, are you using `ssh` so it's something like `git@mycompany.bitbucket.org/project/XXX/repo/XXX` ? The thing is that currently it's hardcoded to use `https` as the protocol, no matter if the repo is cloned over `http`, `https`, `ssh` or some other way. 

_If_ one of the remotes is `http://mycompany.git.internal`, then we can extract the `http` part, but if it's `git@mycomany.git.internal`, then we can only guess, and it's safer to guess `https`.

**Comment by petrisch** [comment]
it is indeed http://mycompany.git.internal, so that could be done.
Hm, didn't know that vim-regex, so I copied it over naivly, which again brings the URL already to the browser.
Thinking about it, I am already quite happy since I can then just remove the s from the URL and voila.
But if there is a safe way to do it, I'd appreciate it as well :smile:

**Comment by mark2185** [comment]
@petrisch could you try out the branch `feature/no-ssl`? 

That should work if the `git` remote is indeed `http://something`, and not `git@something`

**Comment by petrisch** [comment]
Jap that works for me 👍
