### ISSUE TITLE
error on re-sourcing vimrc

### ISSUE THREAD

**Issue by ferdinandyb** [tommcdo/vim-fubitive#21]
If I reload my vimrc I get this error:

```
Error detected while processing /home/fbence/.vim/vimrc[129]..function plug#end[89]..<SNR>10_reload_plugins[2]..<SNR>10_load_plugin[1]..<SNR>10_source[4]..script /home/fbence/.vim/plugged/vim-
fubitive/plugin/fubitive.vim[68]..function <SNR>72_function:

E700: Unknown function: <SNR>10_bitbucket_url
```

**Comment by mark2185** [comment]
Apply this to the beginning of `plugin/fubitive.vim` or just take my fork which already has that.

```diff
+ if exists( 'g:fubitive_loaded' )
+     finish
+ endif
+ let g:fubitive_loaded = 1
```

**Comment by ferdinandyb** [comment]
Hmm, are you not planning to make a pull request for that?

**Comment by mark2185** [comment]
I was, but I saw a few of the issues that seem easily solvable but are ignored, as well as a few PR's that are left opened so I thought the repo was abandoned.

But you're right, maybe the author likes it enough to review/merge it!
