### ISSUE TITLE
fugitive: no GBrowse handler installed for 'ssh://git@bitbucket.company.com:port/project/repo.git'

### ISSUE THREAD

**Issue by h0adp0re** [tommcdo/vim-fubitive#28]
Hello, after the latest update `GBrowse` doesn't work for me anymore, I get the error mentioned in the title:
```
fugitive: no GBrowse handler installed for 'ssh://git@bitbucket.company.local:port/project/repo.git'
```
I have not changed anything. The only configuration for this plugin is still there:

```
let g:fubitive_domain_pattern = 'bitbucket\.company\.local'
```

How to proceed?

**Comment by mark2185** [comment]
Was only `vim-fubitive` updated, or `vim-fugitive` as well?

Do you maybe know the versions before the update?

**Comment by h0adp0re** [comment]
Both were updated. I don't know how to check the versions before the update, but after checking my plugin manager right now, I see that `vim-fubitive` is `(not loaded)`. 

I am using neovim, my plugin manager is packer. And after refactoring the following the plugins work without issue again:

```diff
-    use({
-      "kmARC/vim-fubitive",
-      requires = { "tpope/vim-fugitive" },
-    })
+    use("kmARC/vim-fubitive")
```

So I suppose there is no issue. Only a disclaimer for those who want to define dependencies with packer. Thanks for making me go look! Closing this.
