### ISSUE TITLE
GBrowse does not work with versions other than HEAD

### ISSUE THREAD

**Issue by jbyler** [tommcdo/vim-fubitive#32]
How to reproduce:

1. Open in vim a file that is version controlled with git, hosted on Bitbucket Cloud or Bitbucket Server.
2. Run `:Git blame`
3. Move the cursor down to some older version and press `-` to blame that version.
4. Move the cursor away from the blame window and into the window with the older version of the file.
5. (optional) Select a line with visual mode
6. Run `:GBrowse`

Expected: URL opens showing the file at the revision selected, on the line selected (if any).
Actual: URL opens showing the file at the HEAD revision. Maybe with an error if that file does not exist at that location in the HEAD revision.

Problem: vim-fubitive is using the HEAD revision rather than the revision of the visited file. I will submit a PR with a fix.

**Comment by jbyler** [comment]
Fix is in https://github.com/tommcdo/vim-fubitive/pull/33

**Comment by mark2185** [comment]
Thanks for the fix!
