### ISSUE TITLE
Need to escape `#` in url

### ISSUE THREAD

**Issue by crides** [tommcdo/vim-fubitive#38]
I got this error:
```
E194: No alternate file name to substitute for '#': :silent !xdg-open https://bitbucket.company.com/projects/<project>/<file>?at=<commit>#<line>-<line>
```

Clearly the `#` needs to be escaped

**Comment by mark2185** [comment]
Could you please list the steps needed to reproduce this?

**Comment by crides** [comment]
nvm, issued fired before enough investigation.. turns out I need to escape them myself in the custom `:Browse`
