### ISSUE TITLE
commit empty in three-way diff

### ISSUE THREAD

**Issue by Konfekt** [tommcdo/vim-fubitive#5]
When calling `Gbrowse` from a 3-way diff in a bitbucket repo, `commit` somewhere around

https://github.com/tommcdo/vim-fubitive/blob/ad041a11caf2923415e6d43e0fc4c73fa74dae45/plugin/fubitive.vim#L50

was empty and a path `...bitbucket/src//file.cpp` spat out. Instead, the non-empty branch name `master` could have been used to avoid the void between these two slashes.

**Comment by tommcdo** [comment]
I'm unable to reproduce this behaviour. Can you give a bit more detail?

**Comment by mark2185** [comment]
Not reproducible. If the issue occurs again, please reopen.
