### ISSUE TITLE
Unknown function: s:sub in Neovim

### ISSUE THREAD

**Issue by glortho** [tommcdo/vim-fubitive#9]
Thanks for this handy little extension. At least since switching to Neovim I get this error when trying to Gbrowse:
```
Error detected while processing function <SNR>31_Browse[109]..<SNR>101_bitbucket_url:
line   34:
E117: Unknown function: s:sub
E15: Invalid expression: s:sub(root . '/src/' . commit . '/' . path,'/$','')
```
My vimscript is non-existent - is this an easy patch?

**Comment by tommcdo** [comment]
I haven't had a chance to test this yet. Are there any errors at Vim start-up?

**Comment by glortho** [comment]
Thanks for the response @tommcdo. I don't see any errs at startup. What else can I do to facilitate debugging?

**Comment by tommcdo** [comment]
Does it work in Vim? I'm wondering if this is specific to Neovim.

**Comment by glortho** [comment]
Ah I was about to say it was Neovim specific when I realized that I was only getting that error when trying to run `:Gbrowse` from the `:Gblame` buffer. When navigating to a particular commit it works like a charm. Sorry for the noise. (Incidentally it would be great if fugitive could :Gbrowse the commit under the cursor in that buffer. But that's an issue for another time and place.)

**Comment by tommcdo** [comment]
I'm gonna reopen this because I consider it a bug. `:Gbrowse` works in the blame buffer for (at least) GitHub repositories with fugitive.vim out of the box, so it should be supported here, too.

**Comment by mark2185** [comment]
`s:sub` isn't used in the plugin anymore, closing.
